<?php include_once VIEWPATH.'header.phtml';?>
<link rel="stylesheet" style="text/css" href="/public/css/login.css">
<div class="col-md-10"><h1>老友网<small>实现您梦想的网站</small></h1></div>
<div class="col-md-2">联系电话：15651995562</div>
<div class="bg-success login">

    <div class="col-md-8">
        <form action="/login/check.html" method="post" class="form-horizontal">
            <div class="form-group">
                <div class="col-md-4 text-right"><label for="InputPhone">您的手机：</label></div>
                <div class="col-md-8"> <input type="tel" class="form-control" id="InputPhone"  name="phone"></div>

            </div>
            <div class="form-group">
                <div class="col-md-4 text-right"><label for="InputPassword">您的密码：</label></div>

                <div class="col-md-8"><input type="password" class="form-control" id="InputPassword"  name="password"></div>
            </div>
            <div class="form-group">

                <div class="col-md-4 text-right"><label for="InputPassword">验证码：</label></div>
                <div class="col-md-8">
                    <div class="input-group"><input type="text" class="form-control" id="InputPassword" >
                <span class="input-group-btn"><button class="btn btn-default" type="button">发送</button></span></div>

                </div>
                </div>
            <div class="form-group text-center">
                <div class="col-md-4">
                    &nbsp;
                    </div>
                <div class="col-md-8">
            <button type="button" class="btn btn-success" onclick="checkLogin();">开始 </button>
                    </div>
                </div>
        </form>
    </div>
</div>
<script type="text/javascript">

    function  checkLogin()
    {



    }

</script>
<?php include_once VIEWPATH.'footer.phtml';?>
