<?php include_once ADMIN_VIEW_PATH.'header.phtml';?>

<h1 class="text-center">知名网-后台管理系统</h1>
<div class="bg-success login">

    <div class="col-md-8">
        <form action="/admin/login/check" method="get" class="form-horizontal" id="adminform">
            <div class="form-group">
                <div class="col-md-4 text-right"><label for="Username">用户名：</label></div>
                <div class="col-md-8"> <input type="text" class="form-control" id="Username"  name="username"></div>

            </div>
            <div class="form-group">
                <div class="col-md-4 text-right"><label for="InputPassword">密码：</label></div>

                <div class="col-md-8"><input type="password" class="form-control" id="InputPassword"  name="password"></div>
            </div>

            <div class="form-group text-center">
                <div class="col-md-4">
                    &nbsp;
                </div>
                <div class="col-md-8">
                    <button type="button" class="btn btn-success" onclick="checkLogin();">登录 </button>
                </div>
            </div>
        </form>
    </div>
    <script type="text/javascript">

        function  checkLogin()
        {

            $.ajax({

                url:'/admin/login/check',
                data:$('#adminform').serializeArray(),
                dataType:'json',
                type:'post',
                success:function(data){
                    if( data.error){
                        alert(data.message);
                    }else{
                        window.location = '/admin/home/index';
                    }
                }
            })

        }

    </script>
<?php include_once ADMIN_VIEW_PATH.'footer.phtml';?>
